
```{r include=FALSE}
packages <- c("ggplot2", "dplyr", "Rmpfr")
install.packages(setdiff(packages, rownames(installed.packages())))
library(ggplot2)
library(dplyr)
library(Rmpfr)
```

```{r}
# element,link,executor,core,partition,sleeping_guard,sleeping_instantiate,sleeping_apply,total_time,time_tuples,time_instantiate,time_extract,time_broadcast,time_apply
colTypes <- rep("numeric",14)
data <- read.csv(file="x2_x3_4partitions_Jul_1WE.csv", colClasses=colTypes, comment.char = "#")
```

```{r}
raw_df <- data.frame(data)
df <- raw_df %>% 
  group_by(element, link, executor, core, partition,sleeping_guard,sleeping_instantiate,sleeping_apply) %>% 
  summarise(count=length(total_time),total_time.mean = mean(total_time), total_time.sd = sd(total_time), total_time.median = median(total_time),
            time_tuples.mean = mean(time_tuples), time_tuples.sd = sd(time_tuples), time_tuples.median = median(time_tuples),
            time_instantiate.mean = mean(time_instantiate), time_instantiate.sd = sd(time_instantiate), time_instantiate.median = median(time_instantiate),
            time_extract.mean = mean(time_extract), time_extract.sd = sd(time_extract), time_extract.median = median(time_extract),
            time_broadcast.mean = mean(time_broadcast), time_broadcast.sd = sd(time_broadcast), time_broadcast.median = median(time_broadcast),
            time_apply.mean = mean(time_apply), time_apply.sd = sd(time_apply), time_apply.median = median(time_apply)) 
(df <- df[order(df$sleeping_guard), ])
```

```{r}
size = unique(df$element)
sleeping_times = unique(df$sleeping_guard)

df.with_speedups  <- NULL

for (j in size) {
  
  for(i in sleeping_times){
    
    df.size <- df%>%filter(element == j)
    df.size$total_cores = df.size$core * df.size$executor
    df.sleeping <- df.size %>% filter(sleeping_guard == i)
    df.sleeping$sleeping_time <- df.sleeping$sleeping_guard

    df.sleeping = subset(df.sleeping, select = -c(sleeping_guard, sleeping_instantiate, sleeping_apply))
  
    ref_value = df.sleeping %>% filter(partition == min(df.sleeping$partition))
    ref_value.total_time = ref_value$total_time.mean
    ref_value.time_instantiate = ref_value$time_instantiate.mean
    ref_value.time_apply = ref_value$time_apply.mean
    
    df.sleeping["total_time.speedup"] =  ref_value.total_time / df.sleeping$total_time.mean 
    df.sleeping["time_instantiate.speedup"] =  ref_value.time_instantiate / df.sleeping$time_instantiate.mean 
    df.sleeping["time_apply.speedup"] =  ref_value.time_apply / df.sleeping$time_apply.mean 
    
    df.toprint = subset(df.sleeping, select = c(sleeping_time,element,link,executor,core,total_cores,partition,count,total_time.speedup,time_instantiate.speedup,time_apply.speedup))
    #print(df.toprint)
    
    if (is.null(df.with_speedups )) {
      df.with_speedups  = df.toprint
    }else {
      df.with_speedups  = rbind.data.frame(df.with_speedups , df.toprint)
    }
}

}

df.with_speedups
```

dataset x2 (300 elements, 440 links):
avec 250ms:
  - 8 vs 16 : speed up total de 1.77 (phase1: 1.735944; phase2: 1.884280)
  - 8 vs 32 : speed up total de 3 (phase1: 2.888475; phase2: 3.389765)
avec 500ms:
  - 16 vs 32 : speed up total de 1.73 (phase1: 1.711028; phase2: 1.791007)
avec 2 sec:
  - 8 vs 16 : speed up total de 1.83 (phase1: 1.802389; phase2: 1.914326)
  - 8 vs 32 : speed up total de 3.29 (phase1: 2.888475; phase2: 3.210558)

```{r}
size_for_speedup <- unique(df.with_speedups$element)

df.with_speedups%>%filter(element == 300)


for (j in size_for_speedup) {
  print(j)
  df.with_speedups%>%filter(element == j)
  # plot <- ggplot(data=df.sized, aes(x=total_cores, y=total_time.speedup, group=sleeping_time, color=sleeping_time)) + geom_line() + geom_point()
  #print(plot)
}


```


